store-before/config/routes.rb
Store::Application.routes.draw do
  resources :products
  root to: 'products#index'
end

store-before/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :released_on, :category
end

store-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

store-before/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

store-before/app/helpers/application_helper.rb
module ApplicationHelper
end

store-before/app/helpers/products_helper.rb
module ProductsHelper
end

store-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

store-before/app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <tr>
    <th>Product Name</th>
    <th>Category</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= product.category %></td>
    <td><%= product.released_on.strftime("%B %e, %Y") %></td>
    <td><%= number_to_currency(product.price) %></td>
  </tr>
<% end %>
</table>

store-before/app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Released on:</b>
  <%= @product.released_on.strftime("%B %e, %Y") %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category %>
</p>

<%= link_to 'Back', products_path %>